root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ./cmd/internal"
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
